---
openapi: 3.0.0
info:
  title: Create User
  description: This API creates users for the password manager
  contact:
    email: gpal@my.bcit.ca
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: user
  description: Register new password manager account
paths:
  /login/user:
    get:
        tags:
          - user
        summary: gets user from database
        operationId: app.get_password_user
        description: Gets new user readings after the timestamp
        parameters:
          - name: timestamp
            in: query
            description: limits the number of items on a page
            schema:
              type: string
              format: date-time
              example: '2016-08-29T09:12:33.001Z'
        responses:
          '200':
            description: Successfully returned a list of events
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#components/schemas/PasswordmanagerAccount'
          '400':
            description: Invalid request
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message: 
                      type: string
  /user/password:
#    post:
#      tags:
#      - user
#      summary: adds new password
#      description: Adds new password to be manage by user
#      operationId: app.add_new_password
#      requestBody:
#        description: user's password cache
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/UserPasswords'
#      responses:
#        "201":
#          description: Password created
#        "400":
#          description: invalid input, try again
    get:
      tags:
        - user
      summary: gets user from database
      operationId: app.get_user_password
      description: Gets new user's password readings after the timestamp
      parameters:
        - name: timestamp
          in: query
          description: limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29T09:12:33.001Z'
      responses:
        '200':
          description: Successfully returned a list of evernts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/UserPasswords'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
#  /stats:
#    get:
#      summary: Gets the event stats
#        operationId: app.get_stats
#        description: Gets Blood Pressure and Heart Rate processsed statistics
#        responses:
#          '200':
#            description: Successfully returned a list of blood pressure events
#            content:
#              application/json:
#                schema:
#                  type: object
#                  items:
#                    $ref: '#/components/schemas/ReadingStats'
#            '400':
#              description: Invalid request
#              content:
#                application/json:
#                  schema:
#                    type: object
#                    properties:
#                      message:
#                        type: string

components:
  schemas:
    PasswordmanagerAccount:
      required:
      - email
      - name
      - password
      - user_id
      - trace_id
      type: object
      properties:
        user_id:
          type: integer
          example: 100
        name:
          type: string
          example: Gorden Pal
        email:
          type: string
          example: gpal@my.bcit.ca
        password:
          type: string
          example: password
        trace_id:
          type: string
          example: "303"
    UserPasswords:
      required:
      - description
      - password
      - password_id
      - password_hint
      - trace_id
      type: object
      properties:
        password_id:
          type: string
          example: A100
        password:
          type: string
          example: password
        description:
          type: string
          example: describes discrete purpose of managing this password
        password_hint:
          type: string
          example: "password hint"
        trace_id:
          type: string
          example: "304"

